[workspace]
changelog_config = "cliff.toml"

[[package]]
name = "tui-bar-graph"
pr_branch_prefix = "release-plz-tui-bar-graph-"

[[package]]
name = "tui-big-text"
pr_branch_prefix = "release-plz-tui-big-text-"

[[package]]
name = "tui-box-text"
pr_branch_prefix = "release-plz-tui-box-text-"

[[package]]
name = "tui-cards"
pr_branch_prefix = "release-plz-tui-cards-"

[[package]]
name = "tui-popup"
pr_branch_prefix = "release-plz-tui-popup-"

[[package]]
name = "tui-prompts"
pr_branch_prefix = "release-plz-tui-prompts-"

[[package]]
name = "tui-qrcode"
pr_branch_prefix = "release-plz-tui-qrcode-"

[[package]]
name = "tui-scrollview"
pr_branch_prefix = "release-plz-tui-scrollview-"

[[package]]
name = "tui-widgets"
pr_branch_prefix = "release-plz-tui-widgets-"
